### ISSUE TITLE
Global Installation error 

### ISSUE THREAD

**Issue by fussionlab** [pnp/generator-spfx#219]
#### General Information
* [x] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: 10.9.0
* NPM: 6.2.0

####Getting a Global installation error 

Error: ENOENT: no such file or directory, mkdir '......\AppData\Roaming\npm\node_modules\@pnp\node_modules\@microsoft\generator-sharepoint\lib\generators\applicationCustomizer\templates\react'
    at Object.mkdirSync (fs.js:757:3)
    at Object.<anonymous> (........\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\lib\patch.js:175:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"10.18.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: got@5.7.1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pnp/generator-spfx@1.10.3-alpha10 postinstall: `node lib/patch.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @pnp/generator-spfx@1.10.3-alpha10 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by a1exymoroz** [comment]
When i install via npm, i have the same problem. Yarn fixed this problem.
But Angular Elements is disabled for Angular 8.
How to fix the problem, if #201 is fixed problem with version?

**Comment by fussionlab** [comment]
> When I install via npm, i have the same problem. Yarn fixed this problem.
> But Angular Elements is disabled for Angular 8.
> How to fix the problem, if #201 is the fixed problem with version?

Both npm and yarn have the same issue. is that need to change node downgrade version

**Comment by StfBauer** [comment]
@fussionlab Which version of generator do you use?>
@a1exymoroz Angular 8 is disabled unless you install the Angular CLI. Have you installed the CLI via npm, pnpm or yarn?

**Comment by fussionlab** [comment]
@StfBauer I just managed to install with pnpm, but facing Angular  Elements (Disabled), I have installed latest angular CLI, let me figure it out

**Comment by a1exymoroz** [comment]
@StfBauer I reproduced this problem again and i fixed this problem. I just deleted @pnp/spfx and installed this generator via yeoman, not via npm.
NodeJS: 10.13.0
Angular CLI 8

**Comment by StfBauer** [comment]
@fussionlab as pointed out in issue #216 using pnpm or yarn that should be solved in the next release - rolling out in the next couple of days.

@a1exymoroz thank you for your update. I will try to install the generator via yeoman too. Honestly never tried it out this way. Might be an issue in the generator itself.

**Comment by govinddk4444** [comment]
Downgrading to 1.10.2 worked for me

**Comment by StfBauer** [comment]
Should be fixed in v1.11.0 can someone of you confirm please? Thank you.

**Comment by fussionlab** [comment]
> Should be fixed in v1.11.0 can someone of you confirm please? Thank you.

Great! working fine

**Comment by HarminderSethi** [comment]
still getting the error with 1.11.0

npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"10.16.0","npm":"6.13.1"})
npm WARN notsup Not compatible with your version of node/npm: got@5.7.1

npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN

**Comment by StfBauer** [comment]
@HarminderSethi this is because it is not supported with node 10 only until NodeJS 7.

> npm WARN notsup Unsupported engine for got@5.7.1: wanted: **{"node":">=0.10.0 <7"}** (current: **{"node":"10.16.0","npm":"6.13.1"})**

SPFx comes with a built-in HTTPClient to make requests - https://github.com/SharePoint/sp-dev-training-spfx-graph-3rdpartyapis

**Comment by nithincvpoyyil** [comment]
> @HarminderSethi this is because it is not supported with node 10 only until NodeJS 7.
> 
> > npm WARN notsup Unsupported engine for got@5.7.1: wanted: **{"node":">=0.10.0 <7"}** (current: **{"node":"10.16.0","npm":"6.13.1"})**
> 
> SPFx comes with a built-in HTTPClient to make requests - https://github.com/SharePoint/sp-dev-training-spfx-graph-3rdpartyapis

It might be due to engine-strict=true in .npmrc, try to set it false and install
